insert into drugs (duid, dname, manufacturer, price) values (1, 'Glimepiride', 'Accord Healthcare Inc', '$104.72');
insert into drugs (duid, dname, manufacturer, price) values (2, 'Vancomycin Hydrochloride', 'Hospira, Inc.', '$62.03');
insert into drugs (duid, dname, manufacturer, price) values (3, 'ADVATE', 'Baxter Healthcare Corporation', '$76.84');
insert into drugs (duid, dname, manufacturer, price) values (4, 'Arnica e rad. 20', 'Uriel Pharmacy Inc.', '$117.75');
insert into drugs (duid, dname, manufacturer, price) values (5, 'Dipyridamole', 'Lannett Company, Inc.', '$98.27');
insert into drugs (duid, dname, manufacturer, price) values (6, 'Sleep Aid', 'TOP CARE (Topco Associates LLC)', '$63.75');
insert into drugs (duid, dname, manufacturer, price) values (7, 'Chloraseptic Sore Throat Liquid Center', 'Prestige Brands Holdings, Inc.', '$32.95');
insert into drugs (duid, dname, manufacturer, price) values (8, 'SyAllgen', 'Syntrion GmbH', '$107.18');
insert into drugs (duid, dname, manufacturer, price) values (9, 'Zyprexa', 'Eli Lilly and Company', '$107.21');
insert into drugs (duid, dname, manufacturer, price) values (10, 'Se-Natal 19', 'Seton Pharmaceuticals', '$49.24');
insert into drugs (duid, dname, manufacturer, price) values (11, 'Anti-Aging Vitamin Complex 7-in-1 Broad Spectrum SPF15 Sunscreen', 'Kmart Corporation', '$113.88');
insert into drugs (duid, dname, manufacturer, price) values (12, 'MENHIBRIX', 'GlaxoSmithKline Biologicals SA', '$20.24');
insert into drugs (duid, dname, manufacturer, price) values (13, 'Sertraline Hydrochloride', 'Med-Health Pharma, LLC', '$129.29');
insert into drugs (duid, dname, manufacturer, price) values (14, 'Promethazine Hydrochloride and Codeine Phosphate', 'Atlantic Biologicals Corps', '$125.43');
insert into drugs (duid, dname, manufacturer, price) values (15, 'Tinnitus', 'Apotheca Company', '$30.41');
insert into drugs (duid, dname, manufacturer, price) values (16, 'Loperamide Hydrochloride', 'Preferred Pharmaceuticals, Inc', '$89.08');
insert into drugs (duid, dname, manufacturer, price) values (17, 'Bortons Ethyl Rubbing Alcohol', 'J-Mark International Inc.', '$20.71');
insert into drugs (duid, dname, manufacturer, price) values (18, 'Neuro', 'Deseret Biologicals', '$91.66');
insert into drugs (duid, dname, manufacturer, price) values (19, 'Original Formula Motion Sickness Relief', 'McKesson (Health Mart)', '$22.08');
insert into drugs (duid, dname, manufacturer, price) values (20, 'Heparin Sodium', 'Cantrell Drug Company', '$133.48');
insert into drugs (duid, dname, manufacturer, price) values (21, 'CORYLUS AMERICANA POLLEN', 'ALK-Abello, Inc.', '$135.85');
insert into drugs (duid, dname, manufacturer, price) values (22, 'Foamcoat Antacid', 'Guardian Drug Company', '$56.06');
insert into drugs (duid, dname, manufacturer, price) values (23, 'GALZIN', 'Gate Pharmaceuticals', '$54.18');
insert into drugs (duid, dname, manufacturer, price) values (24, 'Raloxifene Hydrochloride', 'Camber Pharmaceuticals Inc', '$77.03');
insert into drugs (duid, dname, manufacturer, price) values (25, 'DR. OBERON NATURAL BABY', 'Oberon Cosmetic Co., Ltd.', '$10.78');
insert into drugs (duid, dname, manufacturer, price) values (26, 'Metronidazole', 'BluePoint Laboratories', '$89.30');
insert into drugs (duid, dname, manufacturer, price) values (27, 'Prednisone', 'REMEDYREPACK INC.', '$72.15');
insert into drugs (duid, dname, manufacturer, price) values (28, 'Fruit of the Earth Cool Blue Aloe Mist Continuous', 'Fruit of the Earth, Inc.', '$27.94');
insert into drugs (duid, dname, manufacturer, price) values (29, 'NICOTINE', 'Target Corporation', '$122.49');
insert into drugs (duid, dname, manufacturer, price) values (30, 'Benzoyl Peroxide Emollient', 'TAGI Pharma Inc.', '$83.67');
insert into drugs (duid, dname, manufacturer, price) values (31, 'Anti-Bacterial Hand Gel Pink Lemonade', 'The Man Can, LLC', '$50.75');
insert into drugs (duid, dname, manufacturer, price) values (32, 'CYPRESS ESSENCE MASK PACK', 'GREEN LIFE', '$52.35');
insert into drugs (duid, dname, manufacturer, price) values (33, 'Oxaprozin', 'Dr. Reddy''s Laboratories Limited', '$84.99');
insert into drugs (duid, dname, manufacturer, price) values (34, 'ibuprofen', 'CVS Pharmacy', '$131.55');
insert into drugs (duid, dname, manufacturer, price) values (35, 'Dilotab II', 'Zee Medical Inc', '$68.05');
insert into drugs (duid, dname, manufacturer, price) values (36, 'Neutrogena Oil Free Acne Stress Control', 'Neutrogena Corporation', '$25.80');
insert into drugs (duid, dname, manufacturer, price) values (37, 'AKNETROL Acne Treatment', 'ZO Skin Health, Inc.', '$138.81');
insert into drugs (duid, dname, manufacturer, price) values (38, 'ANTIPYRINE AND BENZOCAINE', 'Boca Pharmacal, LLC', '$17.94');
insert into drugs (duid, dname, manufacturer, price) values (39, 'Salsalate', 'Nationwide Laboratories, LLC', '$120.45');
insert into drugs (duid, dname, manufacturer, price) values (40, 'Banana', 'Antigen Laboratories, Inc.', '$38.53');
insert into drugs (duid, dname, manufacturer, price) values (41, 'Ibuprofen softgels', 'AmerisourceBergen Drug Corporation (Good Neighbor Pharmacy)', '$149.93');
insert into drugs (duid, dname, manufacturer, price) values (42, 'Felbamate', 'Amneal Pharmaceuticals', '$5.51');
insert into drugs (duid, dname, manufacturer, price) values (43, 'Acetadryl', 'Physicians Science & Nature Inc.', '$138.60');
insert into drugs (duid, dname, manufacturer, price) values (44, 'Body Raves Antibacterial Hand Sanitizer - Lavender Vanilla', 'Enchante Accessories', '$143.66');
insert into drugs (duid, dname, manufacturer, price) values (45, 'Senna Plus', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', '$120.11');
insert into drugs (duid, dname, manufacturer, price) values (46, 'Fluocinolone Acetonide', 'Physicians Total Care, Inc.', '$58.47');
insert into drugs (duid, dname, manufacturer, price) values (47, 'Ceftriaxone', 'Baxter Healthcare Corporation', '$76.32');
insert into drugs (duid, dname, manufacturer, price) values (48, 'Viscumforce', 'BioActive Nutritional, Inc.', '$43.44');
insert into drugs (duid, dname, manufacturer, price) values (49, 'Dog Fennel', 'Nelco Laboratories, Inc.', '$32.08');
insert into drugs (duid, dname, manufacturer, price) values (50, 'Physicians EZ Use M-pred', 'MedChem Manufacturing Inc. dba Enovachem', '$135.33');
insert into drugs (duid, dname, manufacturer, price) values (51, 'MAPAP', 'State of Florida DOH Central Pharmacy', '$25.92');
insert into drugs (duid, dname, manufacturer, price) values (52, 'NEO CLASSIC HOMME BB', 'THEFACESHOP CO., LTD.', '$135.94');
insert into drugs (duid, dname, manufacturer, price) values (53, 'Cerisa', 'Stratus Pharamceuticals, Inc', '$20.69');
insert into drugs (duid, dname, manufacturer, price) values (54, 'Cephalexin', 'Teva Pharmaceuticals USA Inc', '$139.68');
insert into drugs (duid, dname, manufacturer, price) values (55, 'Glipizide', 'Golden State Medical Supply Inc.', '$42.45');
insert into drugs (duid, dname, manufacturer, price) values (56, 'Fluocinolone Acetonide', 'IGI Labs, Inc.', '$5.76');
insert into drugs (duid, dname, manufacturer, price) values (57, 'Levofloxacin', 'Major Pharmaceuticals', '$86.32');
insert into drugs (duid, dname, manufacturer, price) values (58, 'Bupivacaine Hydrochloride', 'Hospira, Inc.', '$27.06');
insert into drugs (duid, dname, manufacturer, price) values (59, 'Sore Throat Relief', 'Homeocare Laboratories', '$10.49');
insert into drugs (duid, dname, manufacturer, price) values (60, 'Morphine Sulfate', 'Mylan Pharmaceuticals Inc.', '$90.80');
insert into drugs (duid, dname, manufacturer, price) values (61, 'Doxazosin mesylate', 'Golden State Medical Supply, Inc.', '$27.13');
insert into drugs (duid, dname, manufacturer, price) values (62, 'Lansoprazole', 'Rebel Distributors Corp', '$139.76');
insert into drugs (duid, dname, manufacturer, price) values (63, 'NIFEDIPINE', 'STAT RX USA LLC', '$13.21');
insert into drugs (duid, dname, manufacturer, price) values (64, 'Itchy Gone', 'Apotheca Company', '$129.10');
insert into drugs (duid, dname, manufacturer, price) values (65, 'MELOXICAM', 'Direct Rx', '$148.48');
insert into drugs (duid, dname, manufacturer, price) values (66, 'American Infection Control Antiseptic Body Wipes', 'American Infection Control, Inc.', '$88.23');
insert into drugs (duid, dname, manufacturer, price) values (67, 'Ciprofloxacin', 'Carlsbad Technology, Inc.', '$29.84');
insert into drugs (duid, dname, manufacturer, price) values (68, 'Good Neighbor Pharmacy Cough DM ER', 'Amerisource Bergen', '$66.28');
insert into drugs (duid, dname, manufacturer, price) values (69, 'A and D Original', 'MSD Consumer Care, Inc.', '$21.19');
insert into drugs (duid, dname, manufacturer, price) values (70, 'No7 Soft and Sheer Tinted Moisturiser Fair', 'BCM Cosmetique SAS', '$87.13');
insert into drugs (duid, dname, manufacturer, price) values (71, 'Boscia BB Broad Spectrum SPF 27 PA Self Adjusting Shade', 'Boscia LLC', '$50.71');
insert into drugs (duid, dname, manufacturer, price) values (72, 'METOPROLOL TARTRATE', 'DIRECT RX', '$5.65');
insert into drugs (duid, dname, manufacturer, price) values (73, 'Thyrolar', 'Forest Laboratories, Inc', '$87.13');
insert into drugs (duid, dname, manufacturer, price) values (74, 'MUSHROOM', 'ALK-Abello, Inc.', '$134.69');
insert into drugs (duid, dname, manufacturer, price) values (75, 'PLEASURE GARDEN HOMME SPORTS MASK', 'NATURE REPUBLIC CO., LTD.', '$123.48');
insert into drugs (duid, dname, manufacturer, price) values (76, 'Benzoyl Peroxide', 'Harris Pharmaceutical, Inc.', '$45.32');
insert into drugs (duid, dname, manufacturer, price) values (77, 'Ultramicrosize Griseofulvin', 'RiconPharma LLC.', '$88.78');
insert into drugs (duid, dname, manufacturer, price) values (78, 'Ban', 'Kao Brands Company', '$8.71');
insert into drugs (duid, dname, manufacturer, price) values (79, 'members mark famotidine', 'Sam''s West Inc', '$53.61');
insert into drugs (duid, dname, manufacturer, price) values (80, 'Clotrimazole', 'Preferred Pharmaceuticals, Inc.', '$76.05');
insert into drugs (duid, dname, manufacturer, price) values (81, 'Artificial Tears', 'Akorn, Inc.', '$94.47');
insert into drugs (duid, dname, manufacturer, price) values (82, 'Heart Ache', 'King Bio Inc.', '$133.40');
insert into drugs (duid, dname, manufacturer, price) values (83, 'Warfarin Sodium', 'Bryant Ranch Prepack', '$39.91');
insert into drugs (duid, dname, manufacturer, price) values (84, 'smart sense acid reducer', 'Kmart Corporation', '$147.66');
insert into drugs (duid, dname, manufacturer, price) values (85, 'NARS ALL DAY LUMINOUS FOUNDATION', 'NARS COSMETICS', '$28.30');
insert into drugs (duid, dname, manufacturer, price) values (86, 'Peptic Relief', 'Select Brand', '$100.41');
insert into drugs (duid, dname, manufacturer, price) values (87, 'Head and Shoulders', 'Procter & Gamble Manufacturing Co.', '$27.54');
insert into drugs (duid, dname, manufacturer, price) values (88, 'VENLAFAXINE HYDROCHLORIDE', 'American Health Packaging', '$110.89');
insert into drugs (duid, dname, manufacturer, price) values (89, 'Metolazone', 'Eon Labs, Inc.', '$77.88');
insert into drugs (duid, dname, manufacturer, price) values (90, 'Quetiapine fumarate', 'REMEDYREPACK INC.', '$18.14');
insert into drugs (duid, dname, manufacturer, price) values (91, 'Advanced Eye Relief/ Dry Eye/ Rejuvenation Lubricant', 'Bausch & Lomb Incorporated', '$139.39');
insert into drugs (duid, dname, manufacturer, price) values (92, 'Levetiracetam', 'Lupin Pharmaceuticals, Inc.', '$145.31');
insert into drugs (duid, dname, manufacturer, price) values (93, 'Quality Choice', 'Chain Drug Marketing Association', '$81.62');
insert into drugs (duid, dname, manufacturer, price) values (94, 'HEMORRHOIDS', 'HOMEOLAB USA INC', '$99.13');
insert into drugs (duid, dname, manufacturer, price) values (95, 'Stila illuminating tinted moisturizer broad spectrum SPF 20', 'Stila Styles, LLC', '$110.36');
insert into drugs (duid, dname, manufacturer, price) values (96, 'PROMETHAZINE HYDROCHLORIDE', 'Golden State Medical Supply, Inc.', '$8.26');
insert into drugs (duid, dname, manufacturer, price) values (97, 'Pollens - Trees, Beech, American Fagus grandifolia', 'Jubilant HollisterStier LLC', '$140.72');
insert into drugs (duid, dname, manufacturer, price) values (98, 'Lisinopril', 'Wockhardt Limited', '$111.22');
insert into drugs (duid, dname, manufacturer, price) values (99, 'ManzanillaSophia', 'LABORATORIOS SOPHIA, S.A. DE C.V.', '$8.16');
insert into drugs (duid, dname, manufacturer, price) values (100, 'CALAN SR', 'G.D. Searle LLC Division of Pfizer Inc', '$56.99');

