-- Orbital Ion Cannon Nuke
--
--DROP TABLE
--	IF EXISTS
--		prescriptions,
--		insuranceplans,
--		individuals,
--		healthpractitioner,
--		companies,
--		clients,
--		covers,
--		drugs,
--		healthfacilities,
--		insuranceclaims,
--		pharmacists,
--		prescriptioncontents,
--		receipts,
--		reimbursed,
--		subscriptions,
--		worksat
--CASCADE;
--
--DROP TYPE
--	IF EXISTS
--		gender,
--		prescriptions,
--		insuranceplans,
--		individuals,
--		healthpractitioner,
--		companies,
--		clients,
--		covers,
--		drugs,
--		healthfacilities,
--		insuranceclaims,
--		pharmacists,
--		prescriptioncontents,
--		receipts,
--		reimbursed,
--		subscriptions,
--		worksat
--CASCADE;
--
